### ISSUE TITLE
Change casing and use CSS & texttransform

### ISSUE THREAD

**Issue by rcass** [cjrt27/Inhabitent#6]
This is happening in a few spots, where in the markup you have written in ALL CAPS, instead of writing in letter casing or lower case.

Here is an example: 
https://github.com/cjrt27/Inhabitent/blob/b9f6a210cf8d7a05ad71da6039204280ec6f210a/themes/inhabitent/single-products.php#L30-L41

Please change the markup to letter casing or lower case. The reason we write like this in the markup is for accessibility. Screen readers will read the word when in letter casing or lower case, but if the word is written in uppercase it will read out letter by letter 😦

**Comment by cjrt27** [comment]
This change has been implemented
